fieldLayouts:
  7cc6cf6b-aed7-477b-b283-4eaf4dcd8a95:
    tabs:
      -
        elements:
          -
            fieldUid: b0154cdc-eac8-4994-a03b-e1088072a5d5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global Site Description'
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
