enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd:
    enabledByDefault: true
    hasUrls: true
    template: _pages/contact
    uriFormat: contact
type: single
