enableVersioning: true
handle: developmentHistory
name: 'Development History'
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd:
    enabledByDefault: true
    hasUrls: true
    template: _pages/developmentHistory
    uriFormat: development-history
type: single
