enableVersioning: true
handle: portfolioPosts
name: 'Portfolio Posts'
propagationMethod: all
siteSettings:
  0cc785f8-a672-4448-9841-1c39b72f75bd:
    enabledByDefault: true
    hasUrls: true
    template: _pages/portfolio/_entry
    uriFormat: 'portfolio/{slug}'
type: channel
